<a href="https://colab.research.google.com/github/AryanPhanse/ml/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy allows several mathematical functions and faster operations

In [1]:
import numpy as np

In [8]:
#create numpy arrays same as 1d array
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)
print(np_array.shape) #shape of array since it is 1d array it gives no of columns in output

[1 2 3 4 5]
(5,)


In [10]:
#2d array
np_array_2d=np.array([[1,2,3],[4,5,6]])
print(np_array_2d)
print(np_array_2d.shape) #2 rows and 3 columns
#converting it to float
np_array_2d=np.array([[1,2,3],[4,5,6]],dtype=float)
print(np_array_2d)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
#creating numpy array of zeroes
x=np.zeros((3,4)) #3 is no of rows and 4 is no of columns
print(x)
#creating numpy array of ones
x=np.ones((3,4)) #3 is no of rows and 4 is no of columns
print(x)
#creating numpy array eith specific value
x=np.full((3,4),5) #3 is no of rows and 4 is no of columns, 5 is the value of each element
print(x)
#creating identity matrix
x=np.eye(4) #4x4 matrix since identity matrix is square
print(x)

#creating numpy array with random values
x=np.random.random((3,4)) #3 is no of rows and 4 is no of columns
print(x) # the random values is between 0 to 1
#creating random integer values array within specific range
x=np.random.randint(0,10,(3,4)) #3 is no of rows and 4 is no of columns, 0 to 10 is the range
print(x)
#array of evenly spaced values
x=np.linspace(0,20,5) #0 to 10 is the range and 5 is the no of values
print(x)
#array of evenly spaced values with step value
x=np.arange(0,20,5) #0 to 10 is the range and 5 is the step value
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.92242534 0.39153484 0.53276626 0.28964394]
 [0.65921103 0.18773231 0.97769007 0.86023918]
 [0.97933266 0.05897205 0.81111756 0.31736261]]
[[1 1 0 9]
 [3 0 0 5]
 [3 3 6 1]]
[ 0.  5. 10. 15. 20.]
[ 0  5 10 15]


In [20]:
#converting list to numpy array
list=[1,2,3,4,5]
np_array=np.array(list)
print(np_array)
type(np_array)


[1 2 3 4 5]


numpy.ndarray

In [22]:
#Analysing numpy array
c=np.random.randint(10,100,(3,2))
print(c)
print(c.shape)
print(c.size) #gives total elements
print(c.dtype)

[[93 82]
 [72 62]
 [84 22]]
(3, 2)
6
int64


In [25]:
#mathematical operations on np array
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)
print(a+b)
print(a-b)
#another way to add is
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[2 2 3]
 [6 0 2]
 [3 9 2]]
[[15 12 19]
 [19 15 16]
 [14 16 16]]
[[17 14 22]
 [25 15 18]
 [17 25 18]]
[[-13 -10 -16]
 [-13 -15 -14]
 [-11  -7 -14]]
[[17 14 22]
 [25 15 18]
 [17 25 18]]
[[-13 -10 -16]
 [-13 -15 -14]
 [-11  -7 -14]]
[[ 30  24  57]
 [114   0  32]
 [ 42 144  32]]
[[0.13333333 0.16666667 0.15789474]
 [0.31578947 0.         0.125     ]
 [0.21428571 0.5625     0.125     ]]


In [26]:
#transpose an array
array=np.random.randint(0,10,(2,3))
print(array)
trans=np.transpose(array)
print(trans)
#another way to transpose
trans2=array.T
print(trans2)


[[0 6 2]
 [8 0 6]]
[[0 8]
 [6 0]
 [2 6]]
[[0 8]
 [6 0]
 [2 6]]


In [27]:
#reshaping an array
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
trans=array.reshape(3,2)
print(trans)
print(trans.shape)

[[8 9 7]
 [9 8 9]]
(2, 3)
[[8 9]
 [7 9]
 [8 9]]
(3, 2)
